Reference specific instances of resources
Otherwise this happens with tf 0.12.x:

Error: Missing resource instance key

  on .terraform/modules/cc-user-mattb/iam.tf line 310, in resource "aws_iam_policy_attachment" "read_access_policy_attach":
 310:   policy_arn = "${aws_iam_policy.read_access_policy.arn}"

Because aws_iam_policy.read_access_policy has "count" set, its attributes must
be accessed on specific instances.